export const categoriesAndSubCategories = {
	Cleaning: [
		"House Cleaning services",
		"Deep Cleaning.Disinfecting Services",
		"Move IN & OUT services",
		"Vacation Rental Cleaning",
		"Window Cleaning",
		"Carpet Cleaning Services",
		"Garage Cleaning",
		"Car Washing.Laundry Help",
		"Pressure Washing",
	],
	"Furniture Assembly": [
		"Bed Assembly",
		"Dresser Assembly",
		"Couch Assembly",
		"Dining Assembly",
		"Wardrobe Assembly",
		"Desk Assembly",
	],
	"Mounting & Installation": [
		"Tv Mounting",
		"Shelf Mounting",
		"Ceiling Fan Installation",
		"Hanging Curtains & Installing Blinds",
		"Hang Pictures",
		"Hang Christmas Lights",
	],

	"Moving Services": [
		"Packing services",
		"Unpacking services",
		"Heavy lifting",
		"Local Movers",
		"Junk Removal",
		"Furniture Removal and Movers",
		"Appliances Removal and Movers",
	],
	"Office Services": [
		"Commercial Cleaning",
		"Commercial Handyman",
		"Commercial Painting",
		"Conference Room Setup",
		"Office Housekeeping",
		"Office Movers",
		"Office Relocation",
		"Office Snack Delivery",
		"Office Supply Delivery",
		"Office Furniture Assembly",
		"Office Desk Setup",
		"Office Setup & Organization",
		"Data Entry",
		"Redaction Services",
		"Disinfecting Services",
		"Office Administration",
		"Office Interior Design",
		"Project Coordination",
	],
	"Parties & Events": [
		"Bartending",
		"Help Cooking & Serving Food",
		"Shop For & Install Decorations",
		"Entertain Guests",
		"Event Help & Wait Staff",
		"Event Decorating",
		"Event Staffing",
		"Birthday and Party Planning",
		"Event Marketing",
	],

	"Shopping & Delivery": [
		"Grocery Shopping and Delivery",
		"Running Your Errands",
		"Wait in line",
		"Wait for Delivery",
		"Shipping",
	],

	"Software Engineering": ["Frontend", "Backend", "Full-Stack"],
	"Technical Marketing": [
		"Telephone Support Services",
		"Technical Support",
		"Reporting and Monitoring",
		"Live Chat",
		"Email Management",
		"Interactive Voice Response",
		"Customized CRM Tool",
		"Multilingual Support",
	],

	"Yardwork Services": [
		"Gardening Services",
		"Weed Removal",
		"Lawn Care Services",
		"Lawn Mowing",
		"Landscaping Services",
		"Gutter Cleaning",
		"Tree Trimming Service",
		"Hot Tub Cleaning",
		"Fence Installation & Repair Services",
		"Deck Restoration Services",
		"Patio Furniture Assembly",
		"Fence Staining",
		"Mulching Services",
		"Lawn Fertilizer Service",
		"Hedge Trimming Service",
		"Urban Gardening Service",
		"Leaf Raking & Removal",
	],
	Other: ["Other"],
};
