// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// FREELANCE
export const GET_FREELANCE_LIST = "GET_FREELANCE_LIST";
export const SET_FREELANCE_LIST = "SET_FREELANCE_LIST";
export const SET_FREELANCE_BY_ID = "SET_FREELANCE_BY_ID";

// MY JOBS
export const SET_SAVED_FREELANCE_LIST = "SET_SAVED_FREELANCE_LIST";
export const SET_OFFERED_FREELANCE_LIST = "SET_OFFERED_FREELANCE_LIST";
export const SET_ACCEPTED_FREELANCE_LIST = "SET_ACCEPTED_FREELANCE_LIST";
export const SET_APPLIED_FREELANCE_LIST = "SET_APPLIED_FREELANCE_LIST";

// Post JOBS
export const SET_POSTED_FREELANCE_LIST = "SET_POSTED_FREELANCE_LIST";
export const SET_POSTED_FREELANCE = "SET_POSTED_FREELANCE";

// PROFILE
export const SET_PROFILE = "SET_PROFILE";
export const EDIT_AND_SAVE_PROFILE = "EDIT_AND_SAVE_PROFILE";

// REVIEWS
export const SET_REVIEWS = "SET_REVIEWS";
export const SET_REVIEWS_DATA = "SET_REVIEWS_DATA";