// ALERT
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// AUTH
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// AUTH
export const SET_USER = "SET_USER";
export const SET_AUTH = "SET_AUTH";

// FREELANCE
export const GET_FREELANCE_LIST = "GET_FREELANCE_LIST";
export const SET_FREELANCE_LIST = "SET_FREELANCE_LIST";
export const SET_APPLIED_FREELANCE_ID_LIST = "SET_APPLIED_FREELANCE_ID_LIST";
export const SET_SAVED_FREELANCE_ID_LIST = "SET_SAVED_FREELANCE_ID_LIST";
export const SET_ACCEPTED_FREELANCE_ID_LIST = "SET_ACCEPTED_FREELANCE_ID_LIST";
export const SET_ACCEPTED_FREELANCE_ID_LIST_FOR_REVIEW =
	"SET_ACCEPTED_FREELANCE_ID_LIST_FOR_REVIEW";
export const SET_OFFERED_FREELANCE_ID_LIST = "SET_OFFERED_FREELANCE_ID_LIST";
export const SET_DENIED_FREELANCE_ID_LIST = "SET_DENIED_FREELANCE_ID_LIST";
export const SET_FREELANCE_BY_ID = "SET_FREELANCE_BY_ID";
export const SET_CATEGORY_LIST = "SET_CATEGORY_LIST";
export const SET_SEARCH_QUERY_TERM = "SET_SEARCH_QUERY_TERM";
export const SET_SEARCH_QUERY_RESULT_FREELANCE_LIST =
	"SET_SEARCH_QUERY_RESULT_FREELANCE_LIST";

// MY JOBS
export const SET_SAVED_FREELANCE_LIST = "SET_SAVED_FREELANCE_LIST";
export const SET_OFFERED_FREELANCE_LIST = "SET_OFFERED_FREELANCE_LIST";
export const SET_DENIED_FREELANCE_LIST = "SET_DENIED_FREELANCE_LIST";
export const SET_ACCEPTED_FREELANCE_LIST = "SET_ACCEPTED_FREELANCE_LIST";
export const SET_APPLIED_FREELANCE_LIST = "SET_APPLIED_FREELANCE_LIST";

// Post JOBS
export const SET_POSTED_FREELANCE_LIST = "SET_POSTED_FREELANCE_LIST";
export const SET_POSTED_FREELANCE = "SET_POSTED_FREELANCE";

// Employer
export const SET_FREELANCERS_LIST_FOR_HOMEPAGE =
	"SET_FREELANCERS_LIST_FOR_HOMEPAGE";
export const SET_CANDIDATE_LIST = "SET_CANDIDATE_LIST";
export const SET_OFFERED_FREELANCERS_ID_LIST =
	"SET_OFFERED_FREELANCERS_ID_LIST";
export const SET_DENIED_FREELANCERS_ID_LIST = "SET_DENIED_FREELANCERS_ID_LIST";

// PROFILE
export const SET_PROFILE = "SET_PROFILE";
export const SET_VIEW_PROFILE = "SET_VIEW_PROFILE";
export const EDIT_AND_SAVE_PROFILE = "EDIT_AND_SAVE_PROFILE";

// REVIEWS
export const SET_OWN_PROFILE_REVIEWS = "SET_OWN_PROFILE_REVIEWS";
export const SET_OWN_PROFILE_REVIEWS_DATA = "SET_OWN_PROFILE_REVIEWS_DATA";
export const SET_REVIEWS = "SET_REVIEWS";
export const SET_REVIEWS_DATA = "SET_REVIEWS_DATA";
